name: agentdesk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/agentdesk_logo.png
